### ISSUE TITLE
Padding vertex buffers for aquarium Dawn backend

### ISSUE THREAD

**Issue by shaoboyan** [webatintel/aquarium#13]
Refer to gpuweb [issue 404](https://github.com/gpuweb/gpuweb/issues/404), Dawn, as implementation of WebGPU, requires vertex stride as a multiple of 4 bytes.
Aquarium vertex strides are all happens to be multiple of 4 bytes(Lucky!), but it still needs to take care of this.

**Comment by JiangYizhou** [comment]
Yes, this is really lucky! Vertex buffer are all float type which happen to be multiple of 4 bytes. Thanks for your investigation!
