### ISSUE TITLE
SeaweedPer uniform buffer needs to follow std140 layout padding rules

### ISSUE THREAD

**Issue by shaoboyan** [webatintel/aquarium#14]
Aquarium `seaweedVertexShader` has a uniform buffer `seaweedper` [here](https://github.com/webatintel/aquarium/blob/master/shaders/dawn/seaweedVertexShader#L21). It's layout is std140. Refer to [OpenGL 4.5 spec, Chapter 7.6.22](https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf), the padding rules is :
> If the member is an array of scalars or vectors, the base alignment and array
stride are set to match the base alignment of a single array element, according
to rules (1), (2), and (3), and rounded up to the base alignment of a vec4. The
array may have padding at the end; the base offset of the member following
the array is rounded up to the next multiple of the base alignment.

Aquarium needs to follow the padding rules to calculate created buffer size. This will resolve a metal backend debug layer error.

**Comment by JiangYizhou** [comment]
This also fixed an issue that some seaweed doesn't move. Thanks for your effort on this issue!

**Comment by shaoboyan** [comment]
Wow that's really cool ! (But the seaweeds seems moves really slow :P)

**Comment by JiangYizhou** [comment]
The speed is related to the elapsed time, this is updated to time uniform every fps. So I think it's reasonable as long as the seaweeds are moving.
