### ISSUE TITLE
OutsideModelDawn should create large enough buffer for worldUniform 

### ISSUE THREAD

**Issue by shaoboyan** [webatintel/aquarium#15]
`OutsideModelDawn` hits a validation error when executing `diffuseVertexShader` with Metal debug layer on  in Aquarium Dawn backend that `mViewBuffer` is not as large as what shader expected `worldUniforms` to be.

**Comment by JiangYizhou** [comment]
Outside model share the same vertex shader with generic model, and I forgot to match size of world uniform with vertex shader. Thanks for figuring this out.
