### ISSUE TITLE
Current infrastructure ready states

### ISSUE THREAD

**Issue by shaoboyan** [webatintel/aquarium#195]
@hujiajie would you mind list remain works related to infra/rebase to let us understand the status better? Maybe a checklist is great.

**Comment by hujiajie** [comment]
Hi, @shaoboyan

Currently the following changes to `//src/{aquarium-direct-map,common}` are pending / under testing:

- [Factor out the routine for monitor resolution query, bring up GLFW RAII](https://github.com/webatintel/aquarium/pull/194)
- [Implement and deploy the path utility class](https://github.com/webatintel/aquarium/pull/191)
- Add a `--version` flag and print the Git revision extracted from `//build/util/LASTCHANGE`
- Meld `//src/include/CmdArgsHelper.h` into `//src/aquarium-direct-map/Main.cpp`
- Migrate from cxxopts to the Abseil flags library

In the foreseeable future, the following changes are planned:

- Implement the `UNREACHABLE()` macro to replace current `ASSERT(false)` statements
- [Rework window system binding](https://github.com/webatintel/aquarium/issues/100)
